config/routes.rb
Rails.application.routes.draw do
  resources :bank_transactions, :except => [ :destroy, :edit]
  resources :agencies
  resources :bank_accouts 
  resources :dashboard, :only=> [:index]
  devise_for :users

  root 'dashboard#index'

  

end

app/controllers/bank_transactions_controller.rb
class BankTransactionsController < ApplicationController
  before_action :set_bank_transaction, only: [:show, :edit, :update]

  # GET /bank_transactions
  # GET /bank_transactions.json
  def index
    @bank_transactions = BankTransaction.where(user_id: current_user.id)
  end

  # GET /bank_transactions/1
  # GET /bank_transactions/1.json
  def show
  end

  # GET /bank_transactions/new
  def new
    @bank_transaction = BankTransaction.new
  end

  # GET /bank_transactions/1/edit
  def edit
  end

  # POST /bank_transactions
  # POST /bank_transactions.json
  def create
    @bank_transaction = current_user.bank_transactions.new(bank_transaction_params)

    respond_to do |format|
      if @bank_transaction.save
        format.html { redirect_to @bank_transaction, notice: 'Bank transaction was successfully created.' }
        format.json { render :show, status: :created, location: @bank_transaction }
      else
        format.html { render :new }
        format.json { render json: @bank_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_transactions/1
  # PATCH/PUT /bank_transactions/1.json
  def update
    respond_to do |format|
      if @bank_transaction.update(bank_transaction_params)
        format.html { redirect_to @bank_transaction, notice: 'Bank transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_transaction }
      else
        format.html { render :edit }
        format.json { render json: @bank_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_transaction
      @bank_transaction = BankTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_transaction_params
      params.require(:bank_transaction).permit(:data_transaction, :value, :transaction_type, :user_id, :accout_origin_id, :accout_destiny_id)
    end
end

app/helpers/bank_transactions_helper.rb
module BankTransactionsHelper
end

app/views/bank_transactions/_form.html.slim
= form_for @bank_transaction do |f|
  - if @bank_transaction.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bank_transaction.errors.count, "error")} prohibited this bank_transaction from being saved:"
      ul
        - @bank_transaction.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :data_transaction
    = f.date_select :data_transaction
  .field
    = f.label :value
    = f.number_field :value
  .field
    = f.select :transaction_type, BankTransaction.transaction_types.keys,\
    {prompt: 'Selecione uma conta de origem'}, {class: "form-control"}
  .field
    = f.collection_select :accout_origin_id, BankAccout.where(user_id: current_user.id), :id, :accout_number,\
    {prompt: 'Selecione uma conta Sua'}, {class: "accout form-control"}
  .field
    = f.collection_select :accout_destiny_id , BankAccout.where.not(user_id: current_user.id), :id, :show_number_user,\
    {prompt: 'Selecione uma conta de destino'}, {class: "accout form-control"}
  .actions
    = f.submit

app/views/bank_transactions/edit.html.slim
h1 Editing bank_transaction

== render 'form'

=> link_to 'Show', @bank_transaction
'|
=< link_to 'Back', bank_transactions_path

app/views/bank_transactions/index.html.slim
h1 Listing bank_transactions

table.table
  thead
    tr
      th Data transaction
      th Value
      th Type
      th
      

  tbody
    - @bank_transactions.each do |bank_transaction|
      tr
        td = bank_transaction.try(:data_transaction)
        td = bank_transaction.try(:value)
        td = bank_transaction.try(:transaction_type)
        td = link_to 'Show', bank_transaction

br

= link_to 'New Bank transaction', new_bank_transaction_path

app/views/bank_transactions/new.html.slim
h1 New bank_transaction

== render 'form'

= link_to 'Back', bank_transactions_path

app/views/bank_transactions/show.html.slim
p#notice = notice

p
  strong Data transaction:
  = @bank_transaction.data_transaction
p
  strong Value:
  = @bank_transaction.value
p
  strong Type:
  = @bank_transaction.transaction_type
p
  strong Accout origin:
  = @bank_transaction.accout_origin.try(:accout_number)
p
  -if(@bank_transaction.accout_destiny.nil?)
      br
  -else
      strong Accout destiny:
      = @bank_transaction.accout_destiny.try(:accout_number)


=< link_to 'Back', bank_transactions_path