config/routes.rb
Rails.application.routes.draw do
  resources :bank_transactions, :except => [ :destroy, :edit]
  resources :agencies
  resources :bank_accouts 
  resources :dashboard, :only=> [:index]
  devise_for :users

  root 'dashboard#index'

  

end

app/models/bank_accout.rb
class BankAccout < ActiveRecord::Base
  belongs_to :user
  belongs_to :agency
  has_many :bank_transactions

  validates :accout_number, numericality: true, presence: true
  validates :limite, numericality: {greater_than: 0}, presence: true
  validates :agency_id, presence: true
  
  #methods
  def show_number_user
    "#{accout_number + ' - ' + user.email } "
  end
end

app/controllers/bank_accouts_controller.rb
class BankAccoutsController < ApplicationController
  before_action :set_bank_accout, only: [:show, :edit, :update, :destroy]

  # GET /bank_accouts
  # GET /bank_accouts.json
  def index
    @bank_accouts = BankAccout.where(user_id: current_user.id)
  end

  # GET /bank_accouts/1
  # GET /bank_accouts/1.json
  def show
  end

  # GET /bank_accouts/new
  def new
    @bank_accout = BankAccout.new
  end

  # GET /bank_accouts/1/edit
  def edit
  end

  # POST /bank_accouts
  # POST /bank_accouts.json
  def create
    @bank_accout = BankAccout.new(bank_accout_params)
    @bank_accout.user = current_user

    respond_to do |format|
      if @bank_accout.save
        format.html { redirect_to @bank_accout, notice: 'Bank accout was successfully created.' }
        format.json { render :show, status: :created, location: @bank_accout }
      else
        format.html { render :new }
        format.json { render json: @bank_accout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_accouts/1
  # PATCH/PUT /bank_accouts/1.json
  def update
    respond_to do |format|
      if @bank_accout.update(bank_accout_params)
        format.html { redirect_to @bank_accout, notice: 'Bank accout was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_accout }
      else
        format.html { render :edit }
        format.json { render json: @bank_accout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_accouts/1
  # DELETE /bank_accouts/1.json
  def destroy
    @bank_accout.destroy
    respond_to do |format|
      format.html { redirect_to bank_accouts_url, notice: 'Bank accout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_accout
      @bank_accout = BankAccout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_accout_params
      params.require(:bank_accout).permit(:accout_number, :limite, :user_id, :agency_id)
    end
end

app/helpers/bank_accouts_helper.rb
module BankAccoutsHelper
end

app/views/bank_accouts/_form.html.slim
= form_for @bank_accout do |f|
  - if @bank_accout.errors.any?
    #error_explanation
      h2 = "#{pluralize(@bank_accout.errors.count, "error")} prohibited this bank_accout from being saved:"
      ul
        - @bank_accout.errors.full_messages.each do |message|
          li = message
  .
  .form-group
    = f.label "Numero da conta"
    = f.number_field :accout_number, class: "form-control"
  .form-group
    = f.label "Limite" 
    = f.number_field :limite, class: "form-control"
  .form-control
    = f.label "Agencia"
    = collection_select :bank_accout, :agency_id, Agency.all, :id, :agency_number, class: "form-control", prompt: 'Selecione uma opção'
  .actions
  = f.submit "Salvar"

app/views/bank_accouts/edit.html.slim
h1 Editing bank_accout

== render 'form'

=> link_to 'Show', @bank_accout
'|
=< link_to 'Back', bank_accouts_path

app/views/bank_accouts/index.html.slim
h1 Contas Bancárias

table.table.table-striped.table-bordered.table-condensed
  thead
    tr
      th Numero da Conta
      th Limite
      th Agencia
      th Detalhes
      th Editar
      th Excluir

  tbody
    - @bank_accouts.each do |bank_accout|
      tr
        td = bank_accout.try(:accout_number)
        td = bank_accout.try(:limite)
        td = bank_accout.try(:agency).try(:agency_number)
        td = link_to bank_accout, class: "btn btn-info btn-flat" do
          i.fa.fa-eye
          span  Detalhes
          
        td = link_to edit_bank_accout_path(bank_accout), class: "btn btn-warning btn-flat" do
          i.fa.fa-edit
          span  Editar
        td = link_to bank_accout, data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-danger btn-flat" do
          i.fa.fa-trash
          span  Excluir

br
= link_to 'Nova conta bancaria', new_bank_accout_path, class: "btn btn-primary btn-flat"

app/views/bank_accouts/new.html.slim
h1 Nova Conta bancária

== render 'form'

= link_to 'Back', bank_accouts_path, class: "btn btn-warning btn-flat"

app/views/bank_accouts/show.html.slim
p#notice = notice

p
  strong Accout number:
  = @bank_accout.accout_number
p
  strong Limite:
  = @bank_accout.limite
p
  strong User:
  = @bank_accout.user.email
p
  strong Agency:
  = @bank_accout.agency.agency_number

=> link_to 'Edit', edit_bank_accout_path(@bank_accout)

=< link_to 'Back', bank_accouts_path