config/routes.rb
Rails.application.routes.draw do
  resources :bank_transactions, :except => [ :destroy, :edit]
  resources :agencies
  resources :bank_accouts 
  resources :dashboard, :only=> [:index]
  devise_for :users

  root 'dashboard#index'

  

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  has_many :bank_accout

  validates :agency_number,numericality: {greater_than: 2}, presence: true
  validates :address, presence: true, length: { in: 2..200 }
end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController
  before_action :set_agency, only: [:show, :edit, :update, :destroy]

  # GET /agencies
  # GET /agencies.json
  def index
    @agencies = Agency.all
  end

  # GET /agencies/1
  # GET /agencies/1.json
  def show
  end

  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  # POST /agencies.json
  def create
    @agency = Agency.new(agency_params)

    respond_to do |format|
      if @agency.save
        format.html { redirect_to @agency, notice: 'Agency was successfully created.' }
        format.json { render :show, status: :created, location: @agency }
      else
        format.html { render :new }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agencies/1
  # PATCH/PUT /agencies/1.json
  def update
    respond_to do |format|
      if @agency.update(agency_params)
        format.html { redirect_to @agency, notice: 'Agency was successfully updated.' }
        format.json { render :show, status: :ok, location: @agency }
      else
        format.html { render :edit }
        format.json { render json: @agency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agencies/1
  # DELETE /agencies/1.json
  def destroy
    @agency.destroy
    respond_to do |format|
      format.html { redirect_to agencies_url, notice: 'Agency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agency_params
      params.require(:agency).permit(:agency_number, :address, :accout_id)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/views/agencies/_form.html.slim
= form_for @agency do |f|
  - if @agency.errors.any?
    #error_explanation
      h2 = "#{pluralize(@agency.errors.count, "error")} prohibited this agency from being saved:"
      ul
        - @agency.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :agency_number
    = f.number_field :agency_number
  .field
    = f.label :address
    = f.text_field :address
  .actions = f.submit

app/views/agencies/edit.html.slim
h1 Editing agency

== render 'form'

=> link_to 'Show', @agency
'|
=< link_to 'Back', agencies_path

app/views/agencies/index.html.slim
h1 Listing agencies

table.table
  thead
    tr
      th Agency number
      th Address
      th
      th

  tbody
    - @agencies.each do |agency|
      tr
        td = agency.agency_number
        td = agency.address
        td = link_to 'Show', agency
        td = link_to 'Edit', edit_agency_path(agency)
        td = link_to 'Destroy', agency, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Agency', new_agency_path

app/views/agencies/new.html.slim
h1 New agency

== render 'form'

= link_to 'Back', agencies_path

app/views/agencies/show.html.slim
p#notice = notice

p
  strong Agency number:
  = @agency.agency_number
p
  strong Address:
  = @agency.address

=> link_to 'Edit', edit_agency_path(@agency)
'|
=< link_to 'Back', agencies_path