config/routes.rb
Rails.application.routes.draw do
  resources :bank_transactions, :except => [ :destroy, :edit]
  resources :agencies
  resources :bank_accouts 
  resources :dashboard, :only=> [:index]
  devise_for :users

  root 'dashboard#index'

  

end

app/views/layouts/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <%= link_to(root_path, class: "logo") do %>
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>S</b>BC</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Sistema </b>Bancario</span>
    <% end %>
    
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bars"></span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-user"></i>
            <span class="hidden-xs"> <%= current_user.try(:email) %> </span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <i class="fa fa-user fa-4x"></i>
              <p>
                  <%= current_user.try(:email) %>
                <small>Member since <%= current_user.try(:created_at) %></small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-right">
                <%= link_to('Sign out', destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat") %>
              </div>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to(edit_user_registration_path) do %>
            <i class="fa fa-gears"></i>
          <% end %>
          <!-- <a href="/users/edit" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a> -->
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">


    <!-- search form (Optional)
    <form action="#" method="get" class="sidebar-form">
      <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search..."/>
        <span class="input-group-btn">
          <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
      </div>
    </form>
     /.search form -->

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Opções</li>
        <!-- Optionally, you can add icons to the links -->
      <li>
        <%= link_to agencies_path do %>
          <i class="fa fa-bank"></i>
          <span> Agencia</span>
        <% end %>
        </li>
      <li>
        <%= link_to bank_transactions_path	do %>
          <i class="fa fa-exchange"></i>
          <span>Movimentações</span>
        <% end %>
      </li>
      <li>
        <%= link_to bank_accouts_path	do %>
          <i class="fa fa-money"></i>
          <span>Contas Bancárias</span>
        <% end %>
      </li>
      <!-- <li class="treeview">
          <a href="#">
            <i class='fa fa-link'></i>
            <span>Multilevel</span>
            <i class="fa fa-angle-left pull-right"></i>
          </a>
        <ul class="treeview-menu">
          <li>
            <a href="#">Link in level 2</a>
          </li>
          <li>
            <a href="#">Link in level 2</a>
          </li>
        </ul>
      </li> -->
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/admin_lte_2.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Sistema Bancario| Dashboard</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" type="text/css" />
  <link rel="shortcut icon" href="#" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>

<body class="skin-blue sidebar-mini fixed <%= params[:controller].parameterize %> <%= action_name %>">
  <div class="wrapper">

    <%= render partial: 'layouts/admin_lte_2_header' %>

    <%= render partial: 'layouts/admin_lte_2_sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

      <!-- Main content -->
      <section class="content">
        <% if notice %>
          <div class="alert alert-success alert-dismissable">
            <i class="fa fa-check"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= notice %></b>
          </div>
        <% end %>

        <% if alert %>
          <div class="alert alert-danger alert-dismissable">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b><%= alert %></b>
          </div>
        <% end %>
        <%= yield() %>
      </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
      <!-- To the right -->
      <div class="pull-right hidden-xs">
        Anything you want
      </div>
      <!-- Default to the left -->
      <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
    </footer>

      <div class="control-sidebar-bg" style="position: fixed; height: auto;"></div>

  </div><!-- ./wrapper -->

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'validation' %>
</body>
</html>

app/views/layouts/admin_lte_2_login.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Sistema Bancario | Log in</title>
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="/"><b>Sistema </b>Bancario</a>
  </div><!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>
    <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
      <div class="form-group has-feedback">
        <%= f.text_field :email, class: 'form-control', autofocus: true %>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>

      <div class="form-group has-feedback">
        <%= f.password_field :password, class: 'form-control', autocomplete: 'off' %>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div><!-- /.col -->
        <div class="col-xs-4">
          <%= f.submit 'Log in', class: 'btn btn-primary btn-block btn-flat' %>

        </div><!-- /.col -->
      </div>

    <% end %>
  </div><!-- /.login-box-body -->
</div><!-- /.login-box -->

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/layouts/application.slim
doctype html

html lang="pt_br"
  head
    meta charset="UTF-8"/
    meta name="viewport" content="width=device-width, initial-scale=1.0"/
    meta http-equiv="X-UA-Compatible" content="ie=edge"/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    title Sistema Bancario
  body
    .container
      == yield